### ISSUE TITLE
writing idf failed for bldg fids

### ISSUE THREAD

**Issue by Kecheng-Chen** [hues-platform/cesar-p-usage-examples#1]
Hello,

Thank you for release these examples. As I ran the simple_run.py following the instructions, I got an error saying that it failed to write the idf file. Any comments? Thanks in advance.

Here is the debug log file.
[cesarp-debug.log](https://github.com/hues-platform/cesar-p-usage-examples/files/7448091/cesarp-debug.log)

Following are the texts shown in my command window.
(venv-cesar-p) D:\cesar-p-usage-examples\simple_example>python simple_run.py
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
2021-10-30 21:39:17,930 - cesarp.manager.SimulationManager - ERROR - writing idf failed for bldg fids [1,2,3]
Traceback (most recent call last):
  File "simple_run.py", line 48, in <module>
    sim_manager.run_all_steps()
  File "C:\Users\kechengchen\venv-cesar-p\lib\site-packages\cesarp\manager\SimulationManager.py", line 229, in run_all_steps
    raise e
  File "C:\Users\kechengchen\venv-cesar-p\lib\site-packages\cesarp\manager\SimulationManager.py", line 223, in run_all_steps
    self.run_simulations()
  File "C:\Users\kechengchen\venv-cesar-p\lib\site-packages\cesarp\manager\SimulationManager.py", line 320, in run_simulations
    assert self.is_ready_to_run_sim(), "please run create_IDFs before calling run_simulation"
AssertionError: please run create_IDFs before calling run_simulation

**Comment by Kecheng-Chen** [comment]
I did not get the same error as I changed to use the Linux system. Thanks.
